package com.example.demo.model;

import java.util.Objects;

public class Lecture {

	long id;
	String subject;
	String author;
	String preface;

	// below boiler plate code can be generated by Lombok (as discussed during
	// lecture 7)
	Lecture(long id, String subject, String author, String preface) {
		this.id = id;
		this.subject = subject;
		this.author = author;
		this.preface = preface;
	}

	public static LectureBuilder builder() {
		return new LectureBuilder();
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPreface() {
		return preface;
	}

	public void setPreface(String preface) {
		this.preface = preface;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
		Lecture lecture = (Lecture) o;
		return id == lecture.id;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id);
	}

	public static class LectureBuilder {
		private long id;
		private String subject;
		private String author;
		private String preface;

		LectureBuilder() {
		}

		public LectureBuilder id(long id) {
			this.id = id;
			return this;
		}

		public LectureBuilder subject(String subject) {
			this.subject = subject;
			return this;
		}

		public LectureBuilder author(String author) {
			this.author = author;
			return this;
		}

		public LectureBuilder preface(String preface) {
			this.preface = preface;
			return this;
		}

		public Lecture build() {
			return new Lecture(id, subject, author, preface);
		}

		public String toString() {
			return "Lecture.LectureBuilder(id=" + this.id + ", subject=" + this.subject + ", author=" + this.author
					+ ", preface=" + this.preface + ")";
		}
	}
}
